# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_estado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('abiertos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[(b'abierto', b'Abierto '), (b'pendiente', b'Pendiente'), (b'proceso', b'En Proceso'), (b'resuelto', b'Resuelto'), (b'cerrado', b'Cerrado')], default=b'abierto', max_length=10),
        ),
    ]
